In [ ]:
Name : Khandare Pavan Haribhau
Seat No. : CUC003020

In [ ]:
Q1. Write a NumPy program to create a random vector of size 12 and sort it.

In [2]:
import numpy as np

In [22]:
MyArray = np.random.randint(1,50,12) # Vector of random integer values range from 1 to 50, size of 12.

In [23]:
MyArray

array([10, 13, 48, 11, 40, 37, 39, 26, 45, 33, 32, 13])

In [24]:
np.sort(MyArray) # Sorted above array

array([10, 11, 13, 13, 26, 32, 33, 37, 39, 40, 45, 48])

In [ ]:
Q2. For the following array get the shape and reshape in minimum three ways.

In [25]:
Array1 = np.array([[[[1,2],[2,3]], [[2,2],[3,3]]], [[[1,2],[2,3]], [[2,2],[4,4]]]])

In [26]:
Array1

array([[[[1, 2],
         [2, 3]],

        [[2, 2],
         [3, 3]]],


       [[[1, 2],
         [2, 3]],

        [[2, 2],
         [4, 4]]]])

In [27]:
Array1.shape # Shape of Given Array

(2, 2, 2, 2)

In [29]:
Array1.reshape(2,8) # First Reshape

array([[1, 2, 2, 3, 2, 2, 3, 3],
       [1, 2, 2, 3, 2, 2, 4, 4]])

In [30]:
Array1.reshape(8,2) # Second Reshape

array([[1, 2],
       [2, 3],
       [2, 2],
       [3, 3],
       [1, 2],
       [2, 3],
       [2, 2],
       [4, 4]])

In [31]:
Array1.reshape(4,4) # Third Reshape 

array([[1, 2, 2, 3],
       [2, 2, 3, 3],
       [1, 2, 2, 3],
       [2, 2, 4, 4]])

In [ ]:
Q3. Write a NumPy program to compute the mean, standard deviation ,median and variance of a given array.

In [32]:
Array2 = np.array([[ [1,2,3,4,5,6],[7,8,9,10,11,12],[1,3,5,7,9,11]],[[1,2,3,4,5,6],[7,8,9,10,11,12],[1,3,5,7,9,11]]])

In [33]:
Array2

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [ 1,  3,  5,  7,  9, 11]],

       [[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [ 1,  3,  5,  7,  9, 11]]])

In [34]:
Array2.mean() # Mean of above array

6.333333333333333

In [35]:
Array2.std() # Standard Deviation of above array

3.4480268109295333

In [42]:
np.median(Array2) # Median of above array

6.5

In [39]:
Array2.var() # Variance of above array

11.88888888888889

In [ ]:
Q4.Create an array in Numpy of range 12, in 2 by 3 by 2 form, and get the sum at all axis.

In [45]:
Array3 = np.arange(12).reshape(2,3,2)
Array3 # Array of range 12, with 2x3x2 form

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [46]:
Array3.sum(axis=0) # Sum at axis 0

array([[ 6,  8],
       [10, 12],
       [14, 16]])

In [47]:
Array3.sum(axis=1) # Sum at axis 1

array([[ 6,  9],
       [24, 27]])

In [48]:
Array3.sum(axis=2) # Sum at axis 2

array([[ 1,  5,  9],
       [13, 17, 21]])