In [2]:
import numpy as np

In [3]:
MyArray1 = np.array([2,3,5])

In [4]:
MyArray1

array([2, 3, 5])

In [5]:
MyArray1.mean()

3.3333333333333335

In [6]:
MyArray2 = np.array([2,7,11,15,17,21,29])

In [7]:
MyArray2

array([ 2,  7, 11, 15, 17, 21, 29])

In [9]:
np.median(MyArray2)

15.0

In [11]:
MyArray3 = np.array([2,3,4,5,6,7])

In [12]:
MyArray3

array([2, 3, 4, 5, 6, 7])

In [14]:
np.median(MyArray3)

4.5

In [15]:
MyArray3.std()

1.707825127659933

In [16]:
MyArray3.mean()

4.5

In [17]:
MyArray3.var()

2.9166666666666665

In [18]:
MyArray3.prod()

5040

In [19]:
MyArray3.sum()

27

In [20]:
MyArray3.transpose()

array([2, 3, 4, 5, 6, 7])

In [21]:
print(MyArray3.transpose())

[2 3 4 5 6 7]


In [22]:
MyArray3.shape

(6,)

In [23]:
MyArray4 = np.array([[2,3,4],[5,6,7],[8,9,1]])
MyArray4

array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 1]])

In [24]:
MyArray4.shape

(3, 3)

In [27]:
np.ceil(MyArray4)

array([[2., 3., 4.],
       [5., 6., 7.],
       [8., 9., 1.]])

In [28]:
np.floor(MyArray4)

array([[2., 3., 4.],
       [5., 6., 7.],
       [8., 9., 1.]])

In [29]:
MyArray5 = np.array([1.5,0.7,2.1,3.8,9.8,0.6])
MyArray5

array([1.5, 0.7, 2.1, 3.8, 9.8, 0.6])

In [46]:
np.rint(MyArray5)

array([ 2.,  1.,  2.,  4., 10.,  1.])

In [30]:
np.floor(MyArray5) # it shows nearest complete lower value

array([1., 0., 2., 3., 9., 0.])

In [31]:
np.ceil(MyArray5) # it shows nearest complete uppermost value

array([ 2.,  1.,  3.,  4., 10.,  1.])

In [36]:
MyArray6 = np.identity(4,dtype=int)

In [38]:
MyArray6

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [34]:
MyArray6

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [54]:
MyArray7 = np.eye(5,5, k=1)
MyArray7

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [53]:
MyArray7 

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [47]:
MyArray8 = np.array([1.5,0.4,2.1,3.8,9.3,0.6])

In [48]:
MyArray8

array([1.5, 0.4, 2.1, 3.8, 9.3, 0.6])

In [49]:
np.rint(MyArray8) # rint values define as the lowest or uppermost boundry 
# is shown but while doing that minimum step should be follows.

array([2., 0., 2., 4., 9., 1.])

In [59]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [60]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [61]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [62]:
a = np.array([3,2,4])
a

array([3, 2, 4])

In [63]:
b = np.array([4,5,7])
b

array([4, 5, 7])

In [68]:
a+b

array([ 7,  7, 11])

In [69]:
a-b

array([-1, -3, -3])

In [70]:
a*b

array([12, 10, 28])

In [71]:
a/b

array([0.75      , 0.4       , 0.57142857])

In [72]:
(a+b)*b

array([28, 35, 77])

In [78]:
a**4

array([ 81,  16, 256], dtype=int32)

In [74]:
a*a

array([ 9,  4, 16])

In [66]:
np.concatenate((b,a))

array([4, 5, 7, 3, 2, 4])

In [67]:
a+b

array([ 7,  7, 11])

In [80]:
c = np.arange(5)
c

array([0, 1, 2, 3, 4])

In [81]:
c.sum(axis=0)#row wise addition of all element of an array

10

In [92]:
d = np.array([[2,3,4],[4,5,6],[7,8,9]])
d

array([[2, 3, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
d.sum(axis=0)

array([13, 16, 19])

In [95]:
e = d.sum(axis=1)
e

array([ 9, 15, 24])

In [96]:
e.sum(axis=0)

48

In [85]:
np.shape(d)

(2, 3)

In [86]:
np.size(d)

6

In [89]:
d.ndim

2

In [90]:
d.sum(axis=0)

array([ 6,  8, 10])

In [91]:
d.sum(axis=1)

array([ 9, 15])

In [98]:
f = np.identity(5)

In [99]:
f

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [101]:
b = np.array([[1,2,3],[2,3,4]])
b

array([[1, 2, 3],
       [2, 3, 4]])

In [104]:
np.concatenate((f,b),axis=None)

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1., 1., 2., 3., 2., 3., 4.])

In [109]:
np.eye(7,7,k=2, dtype=int)

array([[0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [110]:
np.eye(7,7,k=4, dtype=int)

array([[0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [117]:
k = np.arange(5,12, dtype=float)

In [118]:
k

array([ 5.,  6.,  7.,  8.,  9., 10., 11.])

In [119]:
k.dtype

dtype('float64')

In [114]:
k

array([ 5,  6,  7,  8,  9, 10, 11])

In [116]:
k.dtype

dtype('int32')

In [112]:
k

array([], dtype=int32)

In [124]:
r = np.arange(1,17) 

In [125]:
r

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [137]:
p = r.reshape(4,4)

In [138]:
p

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [139]:
p*0

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [140]:
p/p

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [134]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [135]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [136]:
r*0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])