In [ ]:
# Pavan Khandare
# Worksheet 2

In [ ]:
1) For the following arrays a=[[2,1,3],[4,1,5],[5,3,1]] and b=[[2,2,2]]

In [1]:
import numpy as np

In [4]:
a=np.array([[2,1,3],[4,1,5],[5,3,1]])
a

array([[2, 1, 3],
       [4, 1, 5],
       [5, 3, 1]])

In [5]:
b=np.array([[2,2,2]])
b

array([[2, 2, 2]])

In [6]:
a+b

array([[4, 3, 5],
       [6, 3, 7],
       [7, 5, 3]])

In [7]:
a*b

array([[ 4,  2,  6],
       [ 8,  2, 10],
       [10,  6,  2]])

In [8]:
(a*b)**3

array([[  64,    8,  216],
       [ 512,    8, 1000],
       [1000,  216,    8]], dtype=int32)

In [9]:
a-b

array([[ 0, -1,  1],
       [ 2, -1,  3],
       [ 3,  1, -1]])

In [10]:
(a+b)*(a-b)

array([[ 0, -3,  5],
       [12, -3, 21],
       [21,  5, -3]])

In [11]:
(b**5)+a

array([[34, 33, 35],
       [36, 33, 37],
       [37, 35, 33]])

In [ ]:
2) From the following array find out ceil,floor and rint values

In [ ]:
i. [0.3,0.5,0.9,0.1,0.7]
ii. [1,1.6,2.9,5.8,5.5]
iii. [2.0,3.1,4.3,2.9,4.8]

In [13]:
a=np.array([0.3,0.5,0.9,0.1,0.7])
a

array([0.3, 0.5, 0.9, 0.1, 0.7])

In [14]:
b=np.array([1,1.6,2.9,5.8,5.5])
b

array([1. , 1.6, 2.9, 5.8, 5.5])

In [15]:
c=np.array([2.0,3.1,4.3,2.9,4.8])
c

array([2. , 3.1, 4.3, 2.9, 4.8])

In [16]:
# Floor Value of a
np.floor(a)

array([0., 0., 0., 0., 0.])

In [17]:
# Ceil Value of a
np.ceil(a)

array([1., 1., 1., 1., 1.])

In [19]:
# Rint Value of a
np.rint(a)

array([0., 0., 1., 0., 1.])

In [20]:
# Floor Value of b
np.floor(b)

array([1., 1., 2., 5., 5.])

In [21]:
# Ceil Value of b
np.ceil(b)

array([1., 2., 3., 6., 6.])

In [22]:
# Rint Value of b
np.rint(b)

array([1., 2., 3., 6., 6.])

In [23]:
# Floor Value of c
np.floor(c)

array([2., 3., 4., 2., 4.])

In [24]:
# Ceil Value of c
np.ceil(c)

array([2., 4., 5., 3., 5.])

In [25]:
# Rint Value of c
np.rint(c)

array([2., 3., 4., 3., 5.])

In [ ]:
3) Create an 5 X 5 identity array and concatenate with p=[ [1,2,3],[2,3,4]]

In [26]:
a=np.identity(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
p=np.array([[1,2,3],[2,3,4]])
p

array([[1, 2, 3],
       [2, 3, 4]])

In [35]:
x=np.concatenate((a,p),axis=None)
x

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1., 1., 2., 3., 2., 3., 4.])

In [ ]:
4) Create an 7x7 matrix using eye and first with k=2, K=4 positions

In [36]:
a=np.eye(7,7, k=2)
a

array([[0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [37]:
b=np.eye(7,7, k=4)
b

array([[0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
5) Create 4X4 matirx of your own data and then, make it zero and one.

In [38]:
a=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7]])
a

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [40]:
a=np.zeros((4,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
a=np.ones((4,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])